### ISSUE TITLE
hydra error

### ISSUE THREAD

**Issue by VongolaWu** [blackfeather-wang/AdaFocus#4]
Hi, when I run the program. It will raise an error about the hydra module. 
It seems that the "strict" parameter has already been deprecated from the hydra 1.0 version. But after I remove the "strict".
Another error about the default.yaml appears. 
![image](https://user-images.githubusercontent.com/43229734/137570701-f5e3b8e9-8edb-445d-ae25-22bf48b56444.png)
Also I don't see the "pretty" argument in the "default.yaml" file. 
Thanks for your help in advance.

**Comment by LawrenceXia2008** [comment]
meet too...

**Comment by dreamerlin** [comment]
It seems the version should be 1.0.0

**Comment by VongolaWu** [comment]
> It seems the version should be 1.0.0

I just tried the 1.0.0 version. Still doesn't work.
