### ISSUE TITLE
About eval with SCSampler

### ISSUE THREAD

**Issue by Kaeless** [blackfeather-wang/AdaFocus#6]
A wonderful work!

But I have a problem with evaluation. I can't flnd the code about the article SCSampler:Sampling Salient Clips from Video for Efficient Action Recognition. How can i evaluate these two models on a certain dataset?

**Comment by blackfeather-wang** [comment]
For SCSampler, we cite the re-implementation results from "AR-Net: Adaptive Frame Resolution for Efficient Action Recognition" (https://arxiv.org/pdf/2007.15796.pdf). Their results are widely adopted as baselines in recent papers.
